[package]
name = "poker_hands"
version = "0.1.0"
authors = ["Grayson <grayson.hansard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
